server:
  port: 8000
  error:
    include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
  mvc:
    async:
      request-timeout: -1

  datasource:
    url: jdbc:mariadb://localhost:3312/console?sslmode=disable
    username: admin
    password: wb7WwP1q1z64OUy9jbWR