server:
  port: 8000
  error:
    include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
  mvc:
    async:
      request-timeout: -1
  jackson:
    time-zone: America/Guatemala

  datasource:
    url: jdbc:mysql://3.12.123.213:33060/core
    username: root
    password: dNRiahnuPKixosJ4jADqh37kmvLPVKni26A

  mail:
    host: smtp.gmail.com
    port: 587
    username: bydtesis@gmail.com
    password: okvceiaguysksdbe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

parking:
    origin-email: "bydtesis@gmail.com"
    reply-email: "bydtesis@gmail.com"